version: '3.6'
services:
  selenium:
    container_name: ddev-${DDEV_SITENAME}-chrome
    image: selenium/standalone-chrome:3.12
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT
    environment:
      - VIRTUAL_HOST=${DDEV_SITENAME}.${DDEV_TLD}
      - HTTP_EXPOSE=4444
    external_links:
      - ddev-router:${DDEV_SITENAME}.${DDEV_TLD}
